// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnld35eKhFy6Qd4v2oW7q8zEr9ybbu_-E',
    appId: '1:23124983812:web:64dfa85e5fc0801a75b551',
    messagingSenderId: '23124983812',
    projectId: 'banana-minntoko',
    authDomain: 'banana-minntoko.firebaseapp.com',
    storageBucket: 'banana-minntoko.appspot.com',
    measurementId: 'G-KVQG8M2HD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ3d_CHTmWQxZeRlDAM5vHZYG4OIgpH1E',
    appId: '1:23124983812:android:9d51d197de55f58575b551',
    messagingSenderId: '23124983812',
    projectId: 'banana-minntoko',
    storageBucket: 'banana-minntoko.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr2-pPj7XuePs1KuCHxHbxDAihkhMNJzI',
    appId: '1:23124983812:ios:cbfc20bd37ccc84875b551',
    messagingSenderId: '23124983812',
    projectId: 'banana-minntoko',
    storageBucket: 'banana-minntoko.appspot.com',
    iosBundleId: 'com.minntoko.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr2-pPj7XuePs1KuCHxHbxDAihkhMNJzI',
    appId: '1:23124983812:ios:ef56d4c4bc775ad475b551',
    messagingSenderId: '23124983812',
    projectId: 'banana-minntoko',
    storageBucket: 'banana-minntoko.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
